name: Aria - The Kid
favicon: null
layout_spectrum: 0.6053344688843936
typography_spectrum: 0.4379849247634411
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.24981713481247425
  lightness: 0.02623891388066113
  saturation: 0.3678685713093728
  rhythmicContrast: 0.8927484839223325
purpose: []
